name: model-fashion-mnist
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python fashion_mnist_classifier/training/train_and_evaluate.py
          
          # Write your CML report
          cat results.txt >> report.md
          cml-send-comment report.md
